import type { PublicTournamentProjection } from "@/lib/public-tournaments/public-operational.types";

const teamA = {
  name: "Radiant",
  short_name: "RAD",
  slug: "radiant",
  logo_url: null,
};
const teamB = {
  name: "Dire",
  short_name: "DIRE",
  slug: "dire",
  logo_url: null,
};

export const publicTournamentProjectionFixture: PublicTournamentProjection = {
  locale: "en",
  tournament: {
    slug: "dltv-cup",
    tournament_name: "DLTV Cup",
    description: "A community Deadlock tournament.",
    organizer_name: "Deadlock One",
    region: "EU",
    language: "English",
    start_date: "2026-08-10",
    end_date: "2026-08-12",
    timezone: "Europe/Berlin",
    format: "Single elimination",
    prize_pool_text: "$1,000",
    registration_url: "https://example.com/register",
    bracket_url: "https://example.com/bracket",
    discord_url: "https://discord.gg/example",
    stream_url: "https://example.com/stream",
    rules_url: "https://example.com/rules",
    is_online: true,
    max_teams: 16,
    registration_deadline: "2026-08-09T16:00:00.000Z",
    source_updated_at: "2026-07-31T10:00:00.000Z",
  },
  stages: [
    {
      name: "Playoffs",
      slug: "playoffs",
      stage_type: "playoff",
      sequence_number: 1,
      start_at: "2026-08-10T10:00:00Z",
      end_at: "2026-08-12T18:00:00Z",
      timezone: "Europe/Berlin",
      format_text: "Single elimination",
      best_of_default: 3,
      team_count: 8,
      is_online: true,
      location_name: null,
      status: "active",
    },
  ],
  teams: [
    {
      ...teamA,
      region: "EU",
      seed: 1,
      status: "active",
      roster: [
        {
          display_name: "Ace",
          country_code: "DE",
          role: "player",
          is_captain: true,
        },
      ],
    },
    {
      ...teamB,
      region: "NA",
      seed: 2,
      status: "active",
      roster: [],
    },
  ],
  matches: {
    live: [],
    upcoming: [
      {
        public_id: "Match 1",
        stage: { name: "Playoffs", slug: "playoffs", sequence_number: 1 },
        match_number: 1,
        round_name: "Round 1",
        group_name: null,
        scheduled_at: "2026-08-10T12:00:00Z",
        timezone: "Europe/Berlin",
        best_of: 3,
        team_a: teamA,
        team_b: null,
        score_a: null,
        score_b: null,
        status: "scheduled",
        winner: null,
        stream_url: "https://example.com/live",
        vod_url: null,
        duration_seconds: null,
        deadlock_match_id: null,
      },
    ],
    results: [],
    unscheduled: [],
  },
  summary: {
    stages: 1,
    teams: 2,
    upcoming_matches: 1,
    completed_matches: 0,
    live_match: null,
    next_match: null,
    recent_results: [],
  },
};
