import type { Locale } from "@/i18n/config";

const en = {
  title: "Import tournament data",
  description:
    "Parse, validate and preview a workbook before any tournament data changes.",
  source: "1. Source",
  parsing: "2. Parsing",
  mapping: "3. Mapping",
  validation: "4. Validation",
  preview: "5. Preview",
  conflicts: "6. Conflicts",
  confirmation: "7. Confirmation",
  report: "8. Report",
  xlsx: "Upload XLSX",
  google: "Public Google Sheets",
  googlePlaceholder: "https://docs.google.com/spreadsheets/d/…",
  upload: "Parse workbook",
  template: "Detected template",
  status: "Session status",
  sheets: "Detected sheets",
  row: "Source",
  entity: "Entity",
  action: "Proposed action",
  data: "Safe preview",
  errors: "Errors",
  warnings: "Warnings",
  all: "All",
  create: "Create",
  update: "Update",
  conflict: "Conflict",
  invalid: "Invalid",
  skip: "Skipped",
  resolve: "Resolve conflict",
  keep: "Keep existing",
  useSheet: "Use spreadsheet value",
  skipRow: "Skip row",
  link: "Link to existing entity",
  createNew: "Create new entity",
  existingId: "Existing entity UUID",
  highRisk: "I explicitly confirm replacing a completed result",
  confirm: "Apply import atomically",
  cancel: "Cancel session",
  blocked: "Resolve every conflict and invalid row before applying.",
  noSession:
    "Upload a workbook or provide a public Google Sheets URL to begin.",
  mappingRequired:
    "This layout needs explicit column mapping. No data has been written. Re-upload after selecting a supported Guildlock layout.",
  privacy:
    "Private player identifiers are redacted in preview and never included in audit metadata or public output.",
  completed: "Import completed",
  back: "Back to tournament workspace",
  errorPrefix: "Import could not continue",
} as const;

type ImportCopy = { [Key in keyof typeof en]: string };

const ru: ImportCopy = {
  title: "Импорт данных турнира",
  description:
    "Разбор, проверка и предпросмотр таблицы до любых изменений турнира.",
  source: "1. Источник",
  parsing: "2. Разбор",
  mapping: "3. Сопоставление",
  validation: "4. Проверка",
  preview: "5. Предпросмотр",
  conflicts: "6. Конфликты",
  confirmation: "7. Подтверждение",
  report: "8. Отчёт",
  xlsx: "Загрузить XLSX",
  google: "Публичная Google Таблица",
  googlePlaceholder: "https://docs.google.com/spreadsheets/d/…",
  upload: "Разобрать таблицу",
  template: "Определённый шаблон",
  status: "Статус сессии",
  sheets: "Найденные листы",
  row: "Источник",
  entity: "Сущность",
  action: "Предлагаемое действие",
  data: "Безопасный предпросмотр",
  errors: "Ошибки",
  warnings: "Предупреждения",
  all: "Все",
  create: "Создать",
  update: "Обновить",
  conflict: "Конфликт",
  invalid: "Ошибка",
  skip: "Пропущено",
  resolve: "Разрешить конфликт",
  keep: "Сохранить текущее",
  useSheet: "Использовать значение таблицы",
  skipRow: "Пропустить строку",
  link: "Связать с существующей сущностью",
  createNew: "Создать новую сущность",
  existingId: "UUID существующей сущности",
  highRisk: "Я явно подтверждаю замену завершённого результата",
  confirm: "Применить импорт атомарно",
  cancel: "Отменить сессию",
  blocked: "До импорта разрешите все конфликты и исправьте ошибочные строки.",
  noSession:
    "Для начала загрузите таблицу или укажите публичную ссылку Google Sheets.",
  mappingRequired:
    "Для этой структуры нужно явное сопоставление колонок. Данные не записаны. Загрузите поддерживаемый шаблон Guildlock.",
  privacy:
    "Приватные ID игроков скрыты в предпросмотре и не попадают в аудит или публичные данные.",
  completed: "Импорт завершён",
  back: "Назад в кабинет турнира",
  errorPrefix: "Не удалось продолжить импорт",
};

export const getImportCopy = (locale: Locale) => (locale === "ru" ? ru : en);
