export const adminCopy = {
  brand: "DLTV Organizer Portal",
  nav: {
    section: "Admin",
    submissions: "Submissions",
    logout: "Logout",
  },
  login: {
    eyebrow: "DLTV Organizer Portal",
    title: "Admin access",
    description:
      "Enter your admin email. Supabase will send a secure magic link if the address can receive one.",
    emailLabel: "Email address",
    submit: "Send magic link",
    submitting: "Sending magic link…",
    invalidEmail: "Enter a valid email address.",
    genericSuccess:
      "If the address can receive an admin sign-in link, check its inbox.",
    callbackError: "We could not complete sign in. Request a new magic link.",
  },
  unauthorized: {
    title: "Access denied",
    description: "This account cannot access the administration area.",
    back: "Back to login",
  },
  list: {
    eyebrow: "Read-only moderation",
    title: "Tournament submissions",
    description:
      "Review incoming organizer submissions. Editing and status changes are not available in this interface.",
    filters: "Filter submissions",
    status: "Status",
    allStatuses: "All statuses",
    region: "Region",
    startFrom: "Starts from",
    startTo: "Starts to",
    apply: "Apply filters",
    clear: "Clear",
    empty: "No submissions found.",
    error: "Submissions could not be loaded.",
    columns: {
      tournament: "Tournament",
      organizer: "Organizer",
      region: "Region",
      startDate: "Start date",
      status: "Status",
      submittedAt: "Submitted at",
      updatedAt: "Last updated",
      view: "View",
    },
    previous: "Previous page",
    next: "Next page",
  },
  details: {
    back: "Back to submissions",
    tournament: "Tournament",
    organizer: "Organizer",
    links: "Links",
    audit: "Audit history",
    noEvents: "No audit events found.",
    notAvailable: "Not provided",
    online: "Online",
    offline: "Offline",
    consentToPublish: "Consent to publish",
    consentVersion: "Consent version",
    unknownMetadata: "Additional metadata",
  },
  error: {
    title: "Admin area unavailable",
    description: "The requested admin data could not be loaded. Try again.",
    retry: "Try again",
  },
  notFound: {
    title: "Submission not found",
    description: "The requested submission does not exist.",
    back: "Back to submissions",
  },
} as const;
